# -*- coding: utf-8 -*-
"""RockPaperScissors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hh7bwua9kFAn2ib_wRshpe2iPuvcumbq
"""

# match-case statement

import random
def play_rock_paper_scissors():
  """Plays a game of Rock, Paper, Scissors with the user."""
user_choice = input("Enter your choice (rock, paper, or scissors): ").lower()
computer_choice = random.choice(["rock", "paper", "scissors"])
print(f"You chose {user_choice}, computer chose {computer_choice}. \n")
match (user_choice, computer_choice):
  case (user, comp) if user == comp:
    print(f"Both players selected {user}. It's a tie!")
  case ("rock", "scissors") | ("paper", "rock") | ("scissors", "paper"):
    print(f"{user_choice} beats {computer_choice}! You win!")
  case ("rock", "paper") | ("paper", "scissors") | ("scissors", "rock"):
    print(f"{computer_choice} beats {user_choice}! You lose.")
  case _:
    print("Invalid input! You have not entered rock, paper or scissors, try again.")

# Start the game
play_rock_paper_scissors()